Add new Database Migration Service (DMS) resources
traveloka/terraform-aws-resource-naming pull request #61
Opened 2022-07-05 08:18 UTC by ericklow

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Add new Database Migration Service (DMS) resources

***

Release note for [CHANGELOG](https://github.com/traveloka/terraform-aws-resource-naming/blob/master/CHANGELOG.md):

```release-note
FEATURES:

* **New Source:** `dms_endpoint`
* **New Source:** `dms_replication_instance`
* **New Source:** `dms_replication_task`
```

***

Output from `terraform plan` command from changes you propose.

```
$ terraform plan

```

2022-07-07 03:47 UTC, nin9swells requested changes

2022-07-07 03:47 UTC, nin9swells commented on resources.tf
> +    "dms_replication_task"                = "255" # https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateReplicationInstance.html
- Documentation is swapped between dms_replication_instance and dms_replication_task. Please fix
- dms_replication_instance is only 63 character long

2022-07-07 03:47 UTC, nin9swells commented on resources.tf
> +    "dms_endpoint"                        = "255" # https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateEndpoint.html
Since the documentation doesn't tell us limit of dms_endpoint, please ask AWS support about this before we decide to use 255.

2022-07-11 05:51 UTC, ericklow commented on resources.tf
> +    "dms_replication_task"                = "255" # https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateReplicationInstance.html
Updated 
- https://github.com/traveloka/terraform-aws-resource-naming/pull/61/commits/26c7ad413606f46ed2c479509c14ef35170ee1de
- https://github.com/traveloka/terraform-aws-resource-naming/pull/61/commits/86230933065432b43f63ae3f65706f0944e699f9

2022-07-11 05:53 UTC, ericklow commented on resources.tf
> +    "dms_endpoint"                        = "255" # https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateEndpoint.html
Confirmed that it is 255
![image](https://user-images.githubusercontent.com/17837488/178197657-ede1a264-39b4-4b84-8416-dff8441a316d.png). Thanks.

2022-07-11 06:54 UTC, nin9swells approved these changes

2022-07-11 08:27 UTC, nin9swells approved these changes

2022-07-11 08:43 UTC, nin9swells approved these changes

2022-07-11 08:43 UTC, merged